name: Deploy Node.js App to AWS CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to S3
        uses: aws-actions/s3@v1
        with:
          action: "upload"
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          region: ${{ secrets.AWS_REGION }}
          source: dist
          force: true

      - name: Invalidate AWS CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
            DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
            PATHS: "/index.html"
            AWS_REGION: "us-east-1"
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


